### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by waynevanson** [node-3d/webaudio-raub#1]
HI There,

I have a problem on installation via yarn:

https://gist.github.com/waynevanson/2e3bdd68da8f22cb702e5f17c1fc5dcb

If I download just this package, it should work right? I'm running Linux and have never dealt with these kind of issues beforehand. ANY guidance is appreciated.

**Comment by raub** [comment]
Hello, sorry for the delay, I've been offline for quite a while.

So, as I can see the problem has to do with C++ addon compilation during installation. Most likely it is a C++11 related problem.

I have a Linux CI for this package, it shows no sign of errors you have. That means your invironment is probably different. Could you please check which version of GCC (if not CLANG) you have in the system? To compile this addon you will need at least 4.5+

PS: N-API will probably fix that kind of struggle altogether, when I get to it, some day.

**Comment by waynevanson** [comment]
Thank you for replying.

```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

CLANG not installed.

So this package is not using N-API, is that correct?

**Comment by raub** [comment]
The addon is written with V8 api. When I rewrite it to N-API, there will be no compilation step on the user side.

Ok, here's what I found: "gcc-7 requires include <functional> for std::function". So you probably can switch to gcc6 for the installation to succeed. And in the meanwhile I will also add `#include <functional>` to the module, but unsure if today.

Note that this module is far from completion and only few classes work, the rest are yet to be filled with the implementations. So if you find a part of functionality missing, feel free to create more issues or PRs to speed it up.

**Comment by raub** [comment]
This package is now released as N-API addon, so it doesn't have the compilation step during the installation. See webaudio-raub@1.0.0
